---
# vars file for mirror_ocp_images

pip_args: ''

reg: 'registry.redhat.io'
ocp_repo: '{{ reg }}/openshift3'

cluster_images:
  - '{{ ocp_repo }}/apb-base:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-ansible:v3.11'
  - '{{ ocp_repo }}/apb-base:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/apb-tools:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/automation-broker-apb:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/csi-attacher:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/csi-driver-registrar:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/csi-livenessprobe:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/csi-provisioner:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/grafana:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/local-storage-provisioner:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/manila-provisioner:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/mariadb-apb:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/mediawiki:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/mediawiki-apb:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/mysql-apb:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-ansible-service-broker:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-cli:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-cluster-autoscaler:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-cluster-capacity:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-cluster-monitoring-operator:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-console:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-configmap-reloader:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-control-plane:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-deployer:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-descheduler:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-docker-builder:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-docker-registry:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-efs-provisioner:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-egress-dns-proxy:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-egress-http-proxy:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-egress-router:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-haproxy-router:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-hyperkube:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-hypershift:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-keepalived-ipfailover:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-kube-rbac-proxy:v{{ ocp_ver[:4] }}'
  - '{{ ocp_repo }}/ose-kube-state-metrics:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-metrics-server:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-node:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-node-problem-detector:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-operator-lifecycle-manager:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-ovn-kubernetes:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-pod:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-prometheus-config-reloader:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-prometheus-operator:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-recycler:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-service-catalog:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-template-service-broker:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-tests:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/ose-web-console:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/postgresql-apb:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/registry-console:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/snapshot-controller:v{{ ocp_ver }}'
  - '{{ ocp_repo }}/snapshot-provisioner:v{{ ocp_ver }}'
  - '{{ reg }}/rhel7/etcd:3.2.28'

optional_images:
 - '{{ ocp_repo }}/metrics-cassandra:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/metrics-hawkular-metrics:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/metrics-hawkular-openshift-agent:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/metrics-heapster:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/metrics-schema-installer:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/oauth-proxy:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/ose-logging-curator5:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/ose-logging-elasticsearch5:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/ose-logging-eventrouter:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/ose-logging-fluentd:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/ose-logging-kibana5:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/prometheus:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/prometheus-alertmanager:v{{ ocp_ver }}'
 - '{{ ocp_repo }}/prometheus-node-exporter:v{{ ocp_ver }}'
 - '{{ reg }}/cloudforms46/cfme-openshift-postgresql:latest'
 - '{{ reg }}/cloudforms46/cfme-openshift-memcached:latest'
 - '{{ reg }}/cloudforms46/cfme-openshift-app-ui:latest'
 - '{{ reg }}/cloudforms46/cfme-openshift-app:latest'
 - '{{ reg }}/cloudforms46/cfme-openshift-embedded-ansible:latest'
 - '{{ reg }}/cloudforms46/cfme-openshift-httpd:latest'
 - '{{ reg }}/cloudforms46/cfme-httpd-configmap-generator:latest'
 - '{{ reg }}/rhgs3/rhgs-server-rhel7:latest'
 - '{{ reg }}/rhgs3/rhgs-volmanager-rhel7:latest'
 - '{{ reg }}/rhgs3/rhgs-gluster-block-prov-rhel7:latest'
 - '{{ reg }}/rhgs3/rhgs-s3-server-rhel7:latest'

s2i_images:
 - '{{ reg }}/jboss-amq-6/amq63-openshift:v{{ ocp_ver[:4] }}'
 - '{{ reg }}/jboss-datagrid-7/datagrid71-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-datagrid-7/datagrid71-client-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-datavirt-6/datavirt63-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-datavirt-6/datavirt63-driver-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-decisionserver-6/decisionserver64-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-processserver-6/processserver64-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-eap-6/eap64-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-eap-7/eap71-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-webserver-3/webserver31-tomcat7-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/jboss-webserver-3/webserver31-tomcat8-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/openshift3/jenkins-2-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/openshift3/jenkins-agent-maven-35-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/openshift3/jenkins-agent-nodejs-8-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/openshift3/jenkins-slave-base-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/openshift3/jenkins-slave-maven-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/openshift3/jenkins-slave-nodejs-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/mongodb-32-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/mysql-57-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/perl-524-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/php-56-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/postgresql-95-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/python-35-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/redhat-sso-7/sso70-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/ruby-24-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/redhat-openjdk-18/openjdk18-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/redhat-sso-7/sso71-openshift:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/nodejs-6-rhel7:v{{ ocp_ver }}'
 - '{{ reg }}/rhscl/mariadb-101-rhel7:v{{ ocp_ver }}'

additional_images:
 - '{{ ocp_repo }}/ose-efs-provisioner:v{{ ocp_ver }}'
 - 'docker.io/library/registry:2'
