---

- name: check if {{ image_name }} archive exists
  stat: 
    path: "{{ mirror_base }}/ocp-{{ ocp_ver }}/images/infrastructure/{{ image_name | replace('/','-') | replace(':','_') }}.tar"
  register: docker_archive

- name: Archive {{ image_name }}
  docker_image:
    name: "{{ image_name.split(':')[0] }}"
    tag: "{{ image_name.split(':')[1] }}"
    archive_path: "{{ mirror_base }}/ocp-{{ ocp_ver }}/images/infrastructure/{{ image_name | replace('/','-') | replace(':','_') }}.tar"
    source: pull
  when: docker_archive.stat.exists == False

- name: Remove Image from local images
  docker_image:
    name: "{{ image_name.split(':')[0] }}"
    tag: "{{ image_name.split(':')[1] }}"
    state: absent
    force_absent: true
  when: ( cleanup_local_images | bool )
